config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  post 'notifications/create' => 'notifications#create'

  get 'reports/show'

  get 'reports/export_to_excel_users'

  post 'reports/filter' => 'reports#filter'

  root 'static_pages#home'
  get 'successfull_password_changed', to: 'static_pages#password_changed'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'api/v1/users/create' => 'api/v1/users#create', :defaults => {:format => 'json'}

  post '/api/v1/sessions/create_fb' => 'api/v1/sessions#create_fb', :defaults => {:format => 'json'}

  match '*any' => 'api/api#options', :via => [:options]
  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/orders/subregion_options' => 'notifications#subregion_options'

  get '/cantons/subregion_options' => 'notifications#subsubregion_options'

  post "/promotions/filter" => 'promotions#filter'

  post "/events/filter" => 'events#filter'

  post "/stores/filter" => 'stores#filter'

  post "/place_of_interests/filter" => 'place_of_interests#filter'

  resources :promotions

  resources :users

  get 'admin_promotions' => 'promotions#admin_index'

  resources :events

  resources :stores

  resources :place_of_interests

  resources :password_resets, only: [:edit, :update]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sessions
      resources :users
      resources :promotions
      resources :events
      resources :stores
      resources :place_of_interests
      post 'reset_password', to: 'passwords#create'
      post 'update_token_device', to: 'users#update_user_device'

    end
  end

  post '/api/v1/comments/:event_id/:body' => 'api/v1/comments#create'
  post '/api/v1/reviews/:promo_id/rate/:rate' => 'api/v1/reviews#vote'

  get '/api/v1/reviews/:promo_id' => 'api/v1/reviews#show_user_vote'

  get '/api/v1/get_events' => 'api/v1/events#last'

  get '/api/v1/get_last_events' => 'api/v1/events#last'

  get '/api/v1/get_last_projections' => 'api/v1/events#last_projections'

  get '/api/v1/get_last_promotions' => 'api/v1/promotions#last'

  get '/api/v1/get_countries' => 'api/v1/country#index'

  get '/api/v1/comments/:event_id/:index' => 'api/v1/comments#index_for_event'

  get '/api/v1/get_restaurants' => 'api/v1/stores#index_rest'

  get '/api/v1/get_kioscos' => 'api/v1/stores#index_kiosco'

  get '/api/v1/get_enter' => 'api/v1/place_of_interests#index_enter'
  get '/api/v1/get_cult' => 'api/v1/place_of_interests#index_cult'
  get '/api/v1/get_depor' => 'api/v1/place_of_interests#index_depor'
  get '/api/v1/get_adic' => 'api/v1/place_of_interests#index_adic'

  get '/api/v1/restaurant/:pag' => 'api/v1/stores#paginate_rest'

  get '/api/v1/kiosco/:pag' => 'api/v1/stores#paginate_kiosco'

  get '/api/v1/paginate_event/:pag' => 'api/v1/events#paginate_event'

end

app/models/user.rb
class User < ActiveRecord::Base
  #user sabe a quien pertenece
  belongs_to :store
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  #device sabe quien es su dueño
  has_one :device, dependent: :destroy
  belongs_to :role
  attr_accessor :remember_token , :reset_token

  before_save { self.email = email.downcase }

  validates :user_name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false})
  has_secure_password
  validates(:password, length: {minimum: 6}, allow_blank: true)


  accepts_nested_attributes_for :role, update_only: true

  self.per_page = 5

  before_create do |doc|
    doc.api_key = doc.generate_api_key
  end

  #--------------------------------------------------------------------------------

  def web_user
    self.role.role_name == WEB_USER
  end

  #--------------------------------------------------------------------------------

  def admin
    self.role.role_name == ADMIN_USER;
  end

  #--------------------------------------------------------------------------------

  def social_user
    self.role.role_name == SOCIAL_NETWORK_USER;
  end

  #--------------------------------------------------------------------------------

  def app_user
    self.role.role_name == APP_USER;
  end

  #--------------------------------------------------------------------------------

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :

        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #------------------------------------------------------------

  def User.new_token
    SecureRandom.urlsafe_base64;
  end

  #------------------------------------------------------------

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  #------------------------------------------------------------

  def authenticated?( token, attribute = :remember)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  #------------------------------------------------------------

  def forget
    update_attribute(:remember_digest, nil)
  end


  def update_notification_count
    connection = ActiveRecord::Base.connection
    connection.execute("UPDATE users SET users.count_notification = 0;")
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  #------------------------------------------------------------


  #------------------------------------------------------------

  def generate_api_key
    loop do
      token = SecureRandom.base64.tr('+/=', 'Qrt')
      break token unless User.exists?(api_key: token)
    end
  end


end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApiController



  def create
    @role = Role.find_by(role_name: APP_USER)
    @user = User.new(user_params)
    @user.country = params[:country][:name]
    @user.role = @role

    if params[:province].present?
      @user.province = params[:province][:name]
    end
    if params[:city].present?
      @user.city = params[:city][:name]
    end

    begin
      @user.save!

      Device.create!(token_device: params[:registration_id],
                     operative_system: params[:os], user_id: @user.id)

    rescue ActiveRecord::RecordInvalid
      render json: {sucess: '0'}
      return
    end

    return

  end

  #------------------------------------------------------------------------------------------

  def update_user_device
    email = params[:email]
    token_device = params[:token_device]
    os = params[:os]
    begin

      @user = User.find_by_email(email)
      if @user

        device = Device.find_by_user_id(@user.id)
        if device
          device.update!(token_device: token_device, operative_system: os)
        else
          device = Device.new(user_id: @user.id, operative_system: os, token_device: token_device)
          @user.device = device;
          @user.save!
        end
      else
        render json: {error: 'usuario no encontrado'} and return
      end
    rescue Exception => e
      render json: {erro: e.message} and return
    end

    render json: {success: 'true'}

  end

  #------------------------------------------------------------------------------------------

  private

  def user_params
    params.permit(:user_name, :email, :last_name, :first_time, :password,
                  :password_confirmation, :country, :city, :province, :gender,
                  :born_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include CanCan::ControllerAdditions

  load_and_authorize_resource

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update]

  # before_action :admin_user, only: [:destroy, :index]


  def subcategories_options
    render partial: 'users/admin_index'
  end


  def show
    @user = User.find(params[:id])
  end

#------------------------------------------------------------------

  def new
    @user = User.new
  end

#------------------------------------------------------------------

  def create
    @user= User.new(user_params)
    @role = Role.find(params[:role][:id])
    @user.role = @role
    if @user.save
      if params[:user][:store_id].present?
        @store = Store.find(params[:user][:store_id])
        @user.store = @store
        @user.save
      end
      if params[:user][:notifications_number].present?
        @user.count_notification = 0
        @user.save
      end
      redirect_to users_path

    else
      render 'new';
    end

#------------------------------------------------------------------

  end

  def edit
    @user = User.find(params[:id])
  end

#------------------------------------------------------------------

  def update
    @user = User.find(params[:id])


    if @user.update_attributes(user_params)
      if params[:role][:role_id].present?
        @role = Role.find(params[:role][:role_id])
        @user.role = @role
        @user.save
      end
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

#------------------------------------------------------------------

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    @users = User.paginate(page: params[:page], per_page: 4)

  end

#------------------------------------------------------------------

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

#------------------------------------------------------------------

  def index
    if params[:per_page].present?
      User.per_page = params[:per_page]
    end
    @users = User.paginate(page: params[:page])
  end

#------------------------------------------------------------------

  def admin_user
    if !current_user.admin?
      flash[:warning] = "Usted no esta autorizado para ingresar a esta seccion"
      redirect_to root_url
    end

  end

#------------------------------------------------------------------

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :notifications_number, :password,
                                 :password_confirmation, :store_id)
  end

  def role_params
    params.permit(:role_id)
  end


end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  #cant use constan form initilizer/constant.rb the helper have another namespace or scope

  def rol_translator role_name
    if role_name == 'Admin_user'
      return 'Administrador'
    end

    if role_name == 'App_user'
      return 'Usuario Móvil'
    end

    if role_name == 'Web_user'
      return 'Usuario Web'
    end

    if role_name == 'Social_network_user'
      return 'Usuario red Social'
    end
  end

end

app/views/users/_admin_index.html.erb
<div id="sub_cate_select_wrapper">
  <% store_id||= params[:store_id] %>

  <% store = Store.find_by_id(store_id) %>

  <% if store.nil? %>

      <h4> Selecciona un local arriba por favor </h4>

  <% elsif store.promotions.first %>

      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>

        <tr role="row">
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Titulo: activate to sort column ascending" style="width: 176px;">Titulo
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio: activate to sort column ascending" style="width: 116px;">Precio
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio promocional: activate to sort column ascending" style="width: 236px;">Precio
            promocional
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Imagen">Imagen</th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">Acciones</th>
        </tr>
        </thead>

        <tbody class="middle-align">

        <% store.promotions.each do |promotion| %>

            <%= render promotion %>

        <% end %>

        </tbody>
      </table>

  <% else %>
      <h4> Este local no posee promociones </h4>


  <% end %>

</div>
<script>

    $(document).on("ready page:change", function () {
        $('.tag-tooltip').tooltip();
    });
</script>

app/views/users/_role_user.html.erb
<%= f.select("id", Role.all.collect {|role| [ role.role_name, role.id ] }) %>

app/views/users/_select_for_stores.html.erb
<%= label :role, "Gastronomia" %>
<%= select("user", "store_id", Store.all.collect {|store| [ store.name, store.id ] }, {prompt: 'Select Store'},{class: 'form-control'}) %>

app/views/users/_select_for_stores_edit.html.erb
<%= select("user", "store_id", Store.all.collect {|store| [ store.name, store.id ] },{:selected => @user.store.id},{class: 'form-control'}) %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		<%= link_to "| delete",user, method: :delete,
				data: {confirm: "You sure?"}
		 %>
		 <% end %>
</li>

app/views/users/_user_content.html.erb
<% @users.each do |user| %>
    <tr role="row" class="odd">

      <td><%= user.user_name %></td>
      <td><%= user.email %></td>
      <td><%= rol_translator user.role.role_name %></td>
      <td>
        <% if can? :update, @user %>
            <%= link_to "Editar", edit_user_path(user), class: "btn btn-secondary btn-sm btn-icon icon-left" %>
            <% if user != current_user %>
                <%= link_to "Eliminar", "/users/#{user.id}", {data: {confirm: "Esta seguro que desea eliminar este usuario '#{user.user_name}' from your cart?"}, :method => :delete, remote: true, class: "btn btn-danger btn-sm btn-icon icon-left"} %>
            <% end %>
        <% end %>
      </td>
    </tr>
<% end %>

app/views/users/destroy.js.erb
$(".user-index").html("<%= escape_javascript(render 'user_content') %>")

app/views/users/edit.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default" style="width: 100%;">
      <div class="panel-heading">
        <h3 class="panel-title">Nuevo usuario</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :user_name %>
            <%= f.text_field :user_name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= label :role, "Roles" %>

            <%= select("role", "id", Role.all.collect { |role| [role.role_name, role.id] }, {:selected => @user.role.id}, {class: 'form-control'}) %>

            <br>

            <br>

            <div class="set_store">

              <% if @user.store != nil %>
                  <%= render 'select_for_stores_edit' %>

              <% else %>
                  <%= render 'select_for_stores' %>


              <% end %>

              <br>

              <%= f.label :notifications_number, "Numero de notificaciones" %>
              <%= f.text_field :notifications_number, class: 'form-control' %>


            </div>

            <br>
            <br>

            <%= f.submit "Guardar", class: "btn btn-primary", style: 'width:100%;' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    var ready = function () {
        var select_role = $('#role_id')

        if (select_role.val() == '3') {

            $('.set_store').css("display", "block")
        }
        else {
            $('.set_store').css("display", "none")
        }
    }
    $(document).ready(ready);
    $(document).on("page:load", ready);
</script>



<script>
    $('#role_id').change(function () {

        var select_role = $('#role_id')


        if (select_role.val() == '3') {

            $('.set_store').css("display", "block")
        }
        else {
            $('.set_store').css("display", "none")
        }
    });
</script>

app/views/users/index.html.erb
<% provide(:title, 'Usuarios') %>
<h1> Usuarios </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <% if can? :update, @user %>
        <%= link_to 'nuevo usuario', new_user_path, class: "btn btn-primary btn-sm btn-icon icon-left" %>
    <% end %>
  </div>

  <%= will_paginate %>


  <div class="panel-body">
    <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>

        <tr role="row">
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Nombre: activate to sort column ascending" style="width: 20%;">Nombre
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 30%;">Email
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Tipo de usuario: activate to sort column ascending" style="width: 30%;">Tipo de usuario
          </th>

          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending" style="width: 30%;">Acciones</th>
        </tr>
        </thead>

        <tbody class="middle-align user-index">


        <%= render "user_content" %>


        </tbody>
      </table>

      <div class="row">

        <div class="col-md-4">
          <%= will_paginate %>
        </div>
        <div class="col-md-2">
          <br>
          <br>
          <% if will_paginate %>
              <%= select_tag :per_page, "<option>5</option><option>10</option><option>15</option><option>20</option><option>50</option>".html_safe, class: 'from-control' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $('#per_page').change(function () {
        var select = $('#per_page');
        var jsonPost = { per_page: select.val() }


        $.ajax({
            type: 'GET',
            url: '/users/',
            data: jsonPost,
            dataType: 'script'
        });

    });
</script>

app/views/users/index.js.erb
$(".user-index").html("<%= escape_javascript(render 'user_content') %>")

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default" style="width: 100%;">
      <div class="panel-heading">
        <h3 class="panel-title">Nuevo usuario</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :user_name %>
            <%= f.text_field :user_name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= label :role, "Roles" %>

            <%= select("role", "id", Role.all.collect { |role| [role.role_name, role.id] }, {prompt: 'Select Role'}, {class: 'form-control'}) %>

            <br>

            <br>

            <div class="set_store">

              <%= render 'select_for_stores' %>

              <br>


              <%= f.label :notifications_number, "Numero de notificaciones" %>
              <%= f.text_field :notifications_number, class: 'form-control' %>

            </div>

            <br>
            <br>

            <%= f.submit "Crear cuenta", class: "btn btn-primary", style: 'width:100%;' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    var ready = function () {
        $('.set_store').css("display", "none")

    }

    $(document).ready(ready);
    $(document).on('page:load', ready)
</script>



<script>
    $('#role_id').change(function () {

        var select_role = $('#role_id')


        if (select_role.val() == '3') {

            $('.set_store').css("display", "block")
        }
        else {
            $('.set_store').css("display", "none")
        }
    });
</script>

app/views/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
      <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
          <thead>

          <tr role="row">
            <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Nombre: activate to sort column ascending" style="width: 20%;">Nombre
            </th>
            <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending" style="width: 20%;">Descripcion
            </th>

            <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">Acciones</th>
          </tr>
          </thead>

          <tbody class="middle-align place-interest-index">

          <tr role="row" class="odd">

            <td><%= @user.user_name %></td>
            <td><%= @user.email %></td>
            <td><%= rol_translator @user.role.role_name %></td>

          </tr>

          </tbody>
        </table>


      </div>
    </div>
  </div>
</div>