config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  post 'notifications/create' => 'notifications#create'

  get 'reports/show'

  get 'reports/export_to_excel_users'

  post 'reports/filter' => 'reports#filter'

  root 'static_pages#home'
  get 'successfull_password_changed', to: 'static_pages#password_changed'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'api/v1/users/create' => 'api/v1/users#create', :defaults => {:format => 'json'}

  post '/api/v1/sessions/create_fb' => 'api/v1/sessions#create_fb', :defaults => {:format => 'json'}

  match '*any' => 'api/api#options', :via => [:options]
  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/orders/subregion_options' => 'notifications#subregion_options'

  get '/cantons/subregion_options' => 'notifications#subsubregion_options'

  post "/promotions/filter" => 'promotions#filter'

  post "/events/filter" => 'events#filter'

  post "/stores/filter" => 'stores#filter'

  post "/place_of_interests/filter" => 'place_of_interests#filter'

  resources :promotions

  resources :users

  get 'admin_promotions' => 'promotions#admin_index'

  resources :events

  resources :stores

  resources :place_of_interests

  resources :password_resets, only: [:edit, :update]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sessions
      resources :users
      resources :promotions
      resources :events
      resources :stores
      resources :place_of_interests
      post 'reset_password', to: 'passwords#create'
      post 'update_token_device', to: 'users#update_user_device'

    end
  end

  post '/api/v1/comments/:event_id/:body' => 'api/v1/comments#create'
  post '/api/v1/reviews/:promo_id/rate/:rate' => 'api/v1/reviews#vote'

  get '/api/v1/reviews/:promo_id' => 'api/v1/reviews#show_user_vote'

  get '/api/v1/get_events' => 'api/v1/events#last'

  get '/api/v1/get_last_events' => 'api/v1/events#last'

  get '/api/v1/get_last_projections' => 'api/v1/events#last_projections'

  get '/api/v1/get_last_promotions' => 'api/v1/promotions#last'

  get '/api/v1/get_countries' => 'api/v1/country#index'

  get '/api/v1/comments/:event_id/:index' => 'api/v1/comments#index_for_event'

  get '/api/v1/get_restaurants' => 'api/v1/stores#index_rest'

  get '/api/v1/get_kioscos' => 'api/v1/stores#index_kiosco'

  get '/api/v1/get_enter' => 'api/v1/place_of_interests#index_enter'
  get '/api/v1/get_cult' => 'api/v1/place_of_interests#index_cult'
  get '/api/v1/get_depor' => 'api/v1/place_of_interests#index_depor'
  get '/api/v1/get_adic' => 'api/v1/place_of_interests#index_adic'

  get '/api/v1/restaurant/:pag' => 'api/v1/stores#paginate_rest'

  get '/api/v1/kiosco/:pag' => 'api/v1/stores#paginate_kiosco'

  get '/api/v1/paginate_event/:pag' => 'api/v1/events#paginate_event'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :place_of_interest
  has_many :comments, dependent: :destroy
  default_scope -> { order(date: :asc) }
  validates :name, presence: true
  validates :detail, presence: true
  validates :date, presence: true
  mount_uploader :image, PictureUploader
  mount_uploader :logo_sponsor, PictureUploader

  self.per_page = 5


end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::ApiController

  #----------------------------------------------------------------------
  def show
    @event = Event.find(params[:id])
  end

  #----------------------------------------------------------------------

  def comments
    @event = Event.find(params[:id])
    @comments = @event.comments;
  end

  #----------------------------------------------------------------------

  def index_projections
    @projections = Event.where("projection = ?", true)
  end

  #----------------------------------------------------------------------

  def index_events
    date_param = DateTime.now

    begin
      @events = Event.where("projection = :projection_param AND date > :date_param",
                            {projection_param: false, date_param: date_param}).order(date: :desc)

    rescue ActiveRecord::RecordNotFound
      # handle not found error
      render json: {error: 'no se encontro evento alguno en BD'}
      return
    end

  end

  #----------------------------------------------------------------------

  def last
    date_param = DateTime.now

    begin
      @events = Event.where("projection = :projection_param AND date > :date_param",
                            {projection_param: false, date_param: date_param}).order(date: :desc)

    rescue ActiveRecord::RecordNotFound
      # handle not found error
      render json: {error: 'no se encontro evento alguno en BD'}
      return
    end


  end

  #----------------------------------------------------------------------

  def last_projections
    date_param = DateTime.now

    begin
      @projections = Event.where("projection = :projection_param AND date > :date_param",
                                 {projection_param: true, date_param: date_param}).order(date: :desc)
    rescue ActiveRecord::RecordNotFound
      render json: {error: 'no se encontro projections en BD'}
      return
    end


  end

  #----------------------------------------------------------------------

  def paginate_event
    current_page = Integer(params[:pag], 10)
    per_page = 2
    records_fetch_point = (current_page - 1) * per_page

    eve = Event.all.where("date >= :today", {today: Date.today}).limit(per_page).offset(records_fetch_point)
    promo = Promotion.all.where("initial_date >=  :today",
                                {today: Date.today}).limit(per_page).offset(records_fetch_point);
    @events = eve + promo

    #events out of date so when first call to service we delivery last 2 of each objects
    if @events.length == 0 and current_page == 1
      eve = Event.last(2)
      promo = Promotion.last(2)
      @events = eve + promo
    end

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  include CanCan::ControllerAdditions
  load_and_authorize_resource

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :create]
  # before_action :admin_user, only: [:destroy]

  def show
    @event = Event.find(params[:id])
  end

#------------------------------------------------------------------

  def new
    @event = Event.new
  end

#------------------------------------------------------------------
  def create
    @event = current_user.events.new(event_params)
    if params[:event_date].present?
      event_date = params[:event_date]
      time_date = params[:event_time]
      date_string = event_date + " " + time_date +" "+ "-0430"
      event_datetime = DateTime.strptime(date_string, '%m/%d/%Y %H:%M:%S %P %:z')
      @event.date = event_datetime
    end

    if params[:place_of_interest_id].present?
      @event.place_of_interest_id = params[:place_of_interest_id];
      @event.save
    end

    @event.count_notification = 0

    if @event.save
      if params[:image].present?
        @event.image = params[:image]
        @event.save
      end

      if params[:logo_sponsor].present?
        @event.logo_sponsor = params[:logo_sponsor]
        @event.save
      end
      flash[:success] = "Evento Creado"
      redirect_to :action => 'index'
    else
      render 'new';
    end

#------------------------------------------------------------------

  end

  def edit
    @event = Event.find(params[:id])
    if @event.logo_sponsor.url.nil?
      @event.logo_sponsor = '#'
    end
  end

#------------------------------------------------------------------

  def update
    @event = Event.find(params[:id])
    if params[:image].present?
      @event.image = params[:image]
      @event.save
    end

    if params[:event_date].present?
      event_date = params[:event_date]
      time_date = params[:event_time]
      date_string = event_date + " " + time_date +" "+ "-0430"
      event_datetime = DateTime.strptime(date_string, '%m/%d/%Y %H:%M:%S %P %:z')
      @event.date = event_datetime
    end

    if params[:place_of_interest_id].present?
      @event.place_of_interest_id = params[:place_of_interest_id];
      @event.save
    end

    if params[:logo_sponsor].present?
      @event.logo_sponsor = params[:logo_sponsor]
      @event.save
    end

    if @event.update_attributes(event_params)

      if params[:event][:projection] == '1'
        @event.sponsor = ""
        @event.remove_logo_sponsor!
        @event.place_of_interest_id =
            @event.save
      end

      flash[:success] = "Evento actualizado";
      redirect_to :action => 'index'
    else
      render 'edit'
    end
  end

#------------------------------------------------------------------

  def destroy
    Event.find(params[:id]).destroy
    @events = Event.paginate(page: params[:page])
  end

  def index
    if params[:per_page].present?
      Event.per_page = params[:per_page]
    end

    @events = Event.paginate(page: params[:page])
  end


  def filter
    @events = Event.where("lower(name) like (?)", "%" + params[:event_to_search]+"%")
  end

#------------------------------------------------------------------

  private

  def event_params
    params.require(:event).permit(:name, :detail, :projection, :sponsor,
                                  :notification_body, :latitude, :longitude,
                                  :duration, :city, :country, :place_of_interest_id)
  end

end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_content_event.html.erb
<% @events.each do |event| %>
    <tr role="row" class="odd">
      <td> <%= event.name %> </td>
      <% if event.date != nil %>
          <td> <%= event.date.strftime("%d/%m/%Y") %> </td>
      <% else %>
          <td><h5>Proximanete</h5></td>
      <% end %>
      <% if event.projection %>
          <td>Proyeccion </td>
      <% else %>
          <td>Evento</td>

      <% end %>

      <% if event.notification_body != nil %>
          <% if event.notification_body != '' %>
              <td>

                <h5><%= event.count_notification %></h5>

              </td>

              <td>
                <%= link_to "Enviar Notificacion", notifications_new_path(event_id: event.id), class: 'btn btn-info btn-sm btn-icon icon-left' %>
              </td>
          <% else %>
              <td><h5>N/A</h5></td>
              <td><h5>N/A</h5></td>
          <% end %>
      <% else %>
          <td><h5>N/A</h5></td>

          <td><h5>N/A</h5></td>
      <% end %>

      <td>
        <%= link_to 'Editar', edit_event_path(event), class: "btn btn-secondary btn-sm btn-icon icon-left" %>
        <% if current_user.admin || current_user?(event.user) %>
            <%= link_to 'Eliminar', event, method: :delete, remote: true, data: {confirm: "Esta seguro que desea eliminar el evento ?"}, class: "btn btn-danger btn-sm btn-icon icon-left" %>
        <% end %>
      </td>


    </tr>

<% end %>

app/views/events/_sponsor_logo.html.erb
<div class="row" id="row_logo">

  <%= label_tag(name = :Debes_elegir_una_imagen, content_or_options = nil,
                options = {id: 'req_label_logo', style: 'display: none; color: red;'}) %>

  <label id="camara_icon" class="btn glyphicon glyphicon-camera"
         data-toggle="tooltip" title="Añadir foto">
    Logo de patrocinador

    <%= file_field_tag "logo_sponsor", accept: 'image/jpeg,image/gif,image/png', class: 'photo_upload',
                       id: "logo_file" %>
    <%= content_tag(:div, tag(:img, {id: "logo-preview",src: "#", height: "80", width: "150"}),
                    id: "logo-preview_div") %>
  </label>

</div>

<div class="row" id="remove_div_logo">
  <label id="clear-logo" class="btn glyphicon glyphicon-remove"
         onclick="remove_image('#logo_file','#logo-preview')"></label>
</div>

<script>


    $(document).ready(function () {

        var preview = $("#logo-preview");

        $("#logo_file").change(function(event){
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function(e){
                image_base64 = e.target.result;
                preview.attr("src", image_base64);
            };
            reader.readAsDataURL(file);
        });

    });


</script>

app/views/events/_sponsor_logo_edit.html.erb
<div class="row" id="row_logo">

  <%= label_tag(name = :Debes_elegir_una_imagen, content_or_options = nil,
                options = {id: 'req_label_logo', style: 'display: none; color: red;'}) %>

  <label id="camara_icon" class="btn glyphicon glyphicon-camera"
         data-toggle="tooltip" title="Add photo">
    <%= label_tag "Logo de patrocinador" %>
    <%= file_field_tag "logo_sponsor", accept: 'image/jpeg,image/gif,image/png', class: 'photo_upload',
                       id: "logo_file" %>

    <% if @event.logo_sponsor.url.nil? %>

        <%= content_tag(:div, tag(:img, {src: '#', id: "logo-preview", height: "80",
                                         width: "150"}), id: "logo-preview_div") %>


  <% else %>
        <%= content_tag(:div, tag(:img, {src: @event.logo_sponsor.url, id: "logo-preview", height: "80",
                                         width: "150"}), id: "logo-preview_div") %>

    <% end %>
  </label>
</div>

<div class="row" id="remove_div_logo">
  <label id="clear-logo" class="btn glyphicon glyphicon-remove"
         onclick="remove_image('#logo_file','#logo-preview')"></label>
</div>


<script>


    $(document).ready(function () {

        var preview = $("#logo-preview");

        $("#logo_file").change(function (event) {
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function (e) {
                image_base64 = e.target.result;
                preview.attr("src", image_base64);
            };
            reader.readAsDataURL(file);
        });

    });


</script>

app/views/events/destroy.js.erb
$(".event-index").html("<%= escape_javascript(render 'content_event') %>")

app/views/events/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default" style="width: 100%;">
      <div class="panel-heading">
        <h3 class="panel-title">Editar evento</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@event, html: {multipart: true}) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label 'Nombre' %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label 'Detalles' %>
            <%= f.text_area :detail, class: 'form-control' %>

            <%= f.label 'Proyeccion' %>
            <%= f.check_box :projection, class: 'form-control' %>

            <div class="sponsor_div">
              <%= f.label 'Patrocinador', id: 'label_for_sponsor' %>

              <%= f.text_field :sponsor, class: 'form-control' %>
            </div>

            <div id="place_div" style="display: none;">
              <%= f.label 'Sitios', id: 'label_for_sponsor' %>

              <%= f.select(:place_of_interest_id, PlaceOfInterest.all.collect { |p| [p.name, p.id] },
                           prompt: "Eligue un sitios de interes") %>
            </div>

            <div class="sponsor_logo">
              <%= render 'sponsor_logo_edit' %>
            </div>


            <%= f.label 'Duracion' %>

            <%= f.text_field :duration, class: 'form-control' %>

            <% if @event.notification_body %>

                <%= f.label 'Texto de notificacion' %>

                <%= f.text_field :notification_body, class: 'form-control' %>

            <% end %>


            <div class="row">
              <label class="btn glyphicon glyphicon-camera"
                     data-toggle="tooltip" title="Añadir foto">
                Imagen de evento
                <%= file_field_tag "image", accept: 'image/jpeg,image/gif,image/png', class: 'photo_upload',
                                   id: "image_file" %>
                <%= content_tag(:div, tag(:img, {src: @event.image.url, id: "image-preview", height: "80", width: "150"}), id: "image-preview_div") %>
              </label>

            </div>

            <div class="row">
              <label id="clear-logo" class="btn glyphicon glyphicon-remove" onclick="remove_image('#image_file','#image-preview')"></label>
            </div>


            <div class="form-group">

              <div class="col-sm-6">
                <%= f.label :event_date, 'Fecha', class: 'control-label' %>

                <div class='date-and-time'>

                  <input class="form-control datepicker" type="text" value="<%= @event.date.strftime("%m/%d/%Y") %>" name="event_date" id="event_date">
                  <input type="text" class="form-control timepicker" name="event_time" data-template="dropdown" data-show-seconds="true" value="<%= @event.date.strftime("%I:%M%p") %>" data-show-meridian="true" data-minute-step="5" data-second-step="5">


                </div>
              </div>
            </div>

            <br>

            <br>
            <br>
            <br>
            <br>

            <!-- Dirección -->
            <div class="control-group">
              <label>Coordenadas</label>

              <div class="controls row-fluid">
                <%= f.text_field :latitude, :required => true, placeholder: "Latitud", :class => " form-control span12 form-lat", autocomplete: "off" %>
              </div>
              <div class="controls row-fluid">
                <%= f.text_field :longitude, :required => true, placeholder: "Longitud", :class => "form-control span12 form-lng", autocomplete: "off" %>
              </div>

              <%= f.text_field :city, :type => "hidden", :class => "form-city" %>
              <%= f.text_field :country, :type => "hidden", :class => "form-country" %>

            </div>

            <div id="map-wrap">
              <input id="pac-input" class="controls" type="text" placeholder="Enter a Location">

              <div id="map"></div>
            </div>

            <br>
            <br>
            <!-- Dirección -->
            <div class="col-md-3 col-md-offset-3">
              <%= link_to "Cancelar", :back, class: "btn btn-primary", style: 'width:100%;' %>

            </div>

            <div class="col-md-3 ">
              <%= f.submit "Guardar", id: 'submit_event', class: "btn btn-primary", style: 'width:100%;' %>

            </div>

        <% end %>
      </div>
    </div>
  </div>
</div>


<%= javascript_include_tag 'gmap' %>

<script>

    var ready = function () {

        var event_projection = $('#event_projection')

        if (event_projection.is(":checked")) {
            $('.sponsor_logo').css("display", "none");
            $('.sponsor_div').css("display", "none");
            $('#place_div').css("display", "block");

        }

    }

    $(document).ready(ready);
    $(document).on("page:load", ready);
</script>


<script>
    $('#event_projection').click(function () {

        if ($(this).is(":checked")) {
            $('.sponsor_logo').css("display", "none");
            $('.sponsor_div').css("display", "none");
            $('#place_div').css("display", "block");
            document.getElementById("logo_file").required = false;

        }
        else {
            $('.sponsor_logo').css("display", "block");
            $('.sponsor_div').css("display", "block");
            $('#place_div').css("display", "none");
           document.getElementById("logo_file").required = true;

        }

    });


    $(document).ready(function () {

        $('#submit_event').click(function () {

            var y = $("#image-preview").attr('src');

            if (!y) {

                $('#label_field').css('display', 'block');
                alert('Debes completar los campos requeridos');
            }
            if (!$('#event_projection').is(":checked")) {

                var x = document.getElementById("logo-preview").hasAttribute("src");
                if (!x) {
                    $('#req_label_logo').css('display', 'block');
                    alert('Debes completar los campos requeridos');


                }

            }

        });



        var preview = $("#image-preview");

        $("#image_file").change(function(event){
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function(e){
                image_base64 = e.target.result;
                preview.attr("src", image_base64);
            };
            reader.readAsDataURL(file);
        });


    });


</script>

app/views/events/filter.js.erb
$(".event-index").html("<%= escape_javascript(render 'events/content_event') %>")

app/views/events/index.html.erb
<% provide(:title, 'Eventos') %>
<h1> Eventos </h1>


<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'Nuevo evento', new_event_path, class: "btn btn-primary btn-sm btn-icon icon-left" %>
  </div>

  <% if current_user.admin %>

      <div class="row">

        <!--<div class="col-md-2" style="margin-right: -10%;">
          <label for="starts_with" class="control-label">Buscar</label>


        </div>-->


        <div class="col-md-4">
          <input id="event_to_serch" placeholder="Buscar evento por nombre" name="event_to_serch" type="text" class="form-control"/>
        </div>
      </div>


  <% end %>

  <div class="panel-body">
    <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>
        <tr role="row">
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Titulo: activate to sort column ascending" style="width: 15%;">Nombre
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Fecha: activate to sort column ascending" style="width: 15%;">Fecha
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Fecha: activate to sort column ascending" style="width: 15%;">Tipo
          </th>

          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Numero de notificaciones: activate to sort column ascending" style="width: 15%;">Numero
            de notificaciones
          </th>

          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Notificacion: activate to sort column ascending">Notificacion
          </th>

          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">Acciones
          </th>
        </tr>
        </thead>

        <tbody class="middle-align event-index">

        <%= render 'content_event' %>

        </tbody>
      </table>
      <div class="row">

        <div class="col-md-4">
          <%= will_paginate %>
        </div>
        <div class="col-md-2">
          <br>
          <br>
          <% if will_paginate %>
              <%= select_tag :per_page, "<option>5</option><option>10</option><option>15</option><option>20</option><option>50</option>".html_safe, class: 'from-control' %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>
<script>
    $("#event_to_serch").keyup(function (event) {
        var search_field = $('#event_to_serch');


        var jsonPost = { event_to_search: search_field.val().toLowerCase() }


        $.ajax({
            type: 'POST',
            url: '/events/filter',
            data: jsonPost,
            dataType: 'script'
        });


    });
    $('#per_page').change(function () {
        var select = $('#per_page');
        var jsonPost = { per_page: select.val() }


        $.ajax({
            type: 'GET',
            url: '/events/',
            data: jsonPost,
            dataType: 'script'
        });

    });


</script>

app/views/events/index.js.erb
$(".event-index").html("<%= escape_javascript(render 'content_event') %>")

app/views/events/show.html.erb
<% provide(:title, 'Eventos') %>
<h1> Eventos </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'nuevo evento', new_event_path, class:"btn btn-primary btn-sm btn-icon icon-left"  %>
  </div>
  <div class="panel-body">
    <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>
        <tr role="row">
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Titulo: activate to sort column ascending" style="width: 176px;">Nombre
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio: activate to sort column ascending" style="width: 116px;">Detalles
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio promocional: activate to sort column ascending" style="width: 236px;">Fecha
            promocional
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">proyeccion o itinerario</th>
        </tr>
        </thead>

        <tbody class="middle-align">

        <%= render 'content_event' %>

        </tbody>
      </table>

    </div>
  </div>
</div>