config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  post 'notifications/create' => 'notifications#create'

  get 'reports/show'

  get 'reports/export_to_excel_users'

  post 'reports/filter' => 'reports#filter'

  root 'static_pages#home'
  get 'successfull_password_changed', to: 'static_pages#password_changed'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'api/v1/users/create' => 'api/v1/users#create', :defaults => {:format => 'json'}

  post '/api/v1/sessions/create_fb' => 'api/v1/sessions#create_fb', :defaults => {:format => 'json'}

  match '*any' => 'api/api#options', :via => [:options]
  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/orders/subregion_options' => 'notifications#subregion_options'

  get '/cantons/subregion_options' => 'notifications#subsubregion_options'

  post "/promotions/filter" => 'promotions#filter'

  post "/events/filter" => 'events#filter'

  post "/stores/filter" => 'stores#filter'

  post "/place_of_interests/filter" => 'place_of_interests#filter'

  resources :promotions

  resources :users

  get 'admin_promotions' => 'promotions#admin_index'

  resources :events

  resources :stores

  resources :place_of_interests

  resources :password_resets, only: [:edit, :update]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sessions
      resources :users
      resources :promotions
      resources :events
      resources :stores
      resources :place_of_interests
      post 'reset_password', to: 'passwords#create'
      post 'update_token_device', to: 'users#update_user_device'

    end
  end

  post '/api/v1/comments/:event_id/:body' => 'api/v1/comments#create'
  post '/api/v1/reviews/:promo_id/rate/:rate' => 'api/v1/reviews#vote'

  get '/api/v1/reviews/:promo_id' => 'api/v1/reviews#show_user_vote'

  get '/api/v1/get_events' => 'api/v1/events#last'

  get '/api/v1/get_last_events' => 'api/v1/events#last'

  get '/api/v1/get_last_projections' => 'api/v1/events#last_projections'

  get '/api/v1/get_last_promotions' => 'api/v1/promotions#last'

  get '/api/v1/get_countries' => 'api/v1/country#index'

  get '/api/v1/comments/:event_id/:index' => 'api/v1/comments#index_for_event'

  get '/api/v1/get_restaurants' => 'api/v1/stores#index_rest'

  get '/api/v1/get_kioscos' => 'api/v1/stores#index_kiosco'

  get '/api/v1/get_enter' => 'api/v1/place_of_interests#index_enter'
  get '/api/v1/get_cult' => 'api/v1/place_of_interests#index_cult'
  get '/api/v1/get_depor' => 'api/v1/place_of_interests#index_depor'
  get '/api/v1/get_adic' => 'api/v1/place_of_interests#index_adic'

  get '/api/v1/restaurant/:pag' => 'api/v1/stores#paginate_rest'

  get '/api/v1/kiosco/:pag' => 'api/v1/stores#paginate_kiosco'

  get '/api/v1/paginate_event/:pag' => 'api/v1/events#paginate_event'

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :store
  has_many :reviews, dependent: :destroy
  default_scope -> { order(initial_date: :asc) }
  #validates :rate, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  mount_uploader :image, PictureUploader
  scope :starts_with, -> (title) { where("lower(title) like ?", "#{title}%") }

  validates :title,:store, presence: true

  self.per_page = 5

end

app/controllers/api/v1/promotions_controller.rb
class Api::V1::PromotionsController < Api::ApiController

  respond_to :json

  before_action :init

  #----------------------------------------------------------------------

  def init
    @rate_count = 0;
    @reviews_count = 0;
  end

  #----------------------------------------------------------------------

  def index
    @promotions = Promotion.all
  end

  #----------------------------------------------------------------------

  def show


    begin
      @promo = Promotion.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      # handle other ActiveRecord errors
      render json: {error: 'no se encontro esta promocion en BD'}
      return

    end

    @reviews = Review.where("promotion_id = :promotion_id", {promotion_id: @promo.id})

    if @reviews.first

      @reviews.each do |review|

        @rate_count = @rate_count + review.rate;
        @reviews_count += 1;

      end

      @media_rate = @rate_count/@reviews_count

      return
    else
      @media_rate = 'Se el primero en calificarla'
    end
  end


  #----------------------------------------------------------------------

  def vote
    @promo = Promotion.find(params[:id])
    rate = params[:rate]
    @promo.vote_count = rate
    #@promo.summatory += rate;
    if @promo.save
      render json: {sucess: '1'}
    else
      render json: {sucess: '0'}
    end
  end

  #----------------------------------------------------------------------

  def last
    if Promotion.first.nil?
      render json: {error: 'no existen  promociones en BD'}
      return;
    end
    @promotions = []
    promo = Promotion.first
    @promotions.append(promo)
    if Promotion.second
      @promotions.append(Promotion.second)
    end
  end

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :create]

#------------------------------------------------------------------
  def index
    if params[:per_page].present?
      Promotion.per_page = params[:per_page]
    end
    if current_user.admin
      @promotions = Promotion.all.paginate(page: params[:page])
    else
      @promotions = Promotion.where("store_id = ?", current_user.store).paginate(page: params[:page])
    end


  end

  def show
    @promo = Promotion.find(params[:id])
  end


  def new
    @promo = Promotion.new
  end

#------------------------------------------------------------------

  def create
    if current_user.admin
      @promo = Promotion.create(promo_params)

      if params[:initial_date].present?
        init_date = params[:initial_date]
        init_time = params[:initial_time]
        date_string = init_date + " " + init_time +" "+ "-0430"
        event_datetime = DateTime.strptime(date_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.initial_date = event_datetime

        final_date = params[:finish_date]
        final_time = params[:finish_time]
        final_string = final_date + " " + final_time +" "+ "-0430"
        final_datetime = DateTime.strptime(final_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.finish_date = final_datetime
      end

    else
      @promo = Promotion.create(promo_params)
      @promo.store = current_user.store

      if params[:initial_date].present?
        init_date = params[:initial_date]
        init_time = params[:initial_time]
        date_string = init_date + " " + init_time +" "+ "-0430"
        event_datetime = DateTime.strptime(date_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.initial_date = event_datetime

        final_date = params[:finish_date]
        final_time = params[:finish_time]
        final_string = final_date + " " + final_time +" "+ "-0430"
        final_datetime = DateTime.strptime(final_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.finish_date = final_datetime
      end

    end

    @promo.count_notification = 0
    if @promo.save

      if params[:image].present?
        @promo.image = params[:image]
        @promo.save
      end

      flash[:success] = "Promocion Creada!"
      redirect_to promotions_path
    else
      render 'new';
    end

#------------------------------------------------------------------

  end

  def edit
    @promo = Promotion.find(params[:id])
  end

#------------------------------------------------------------------

  def update
    @promo = Promotion.find(params[:id])
    if @promo.update_attributes(promo_params)
      if params[:image].present?
        @promo.image = params[:image]
        @promo.save
      end

      if params[:initial_date].present?
        init_date = params[:initial_date]
        init_time = params[:initial_time]
        date_string = init_date + " " + init_time +" "+ "-0430"
        event_datetime = DateTime.strptime(date_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.initial_date = event_datetime

        final_date = params[:finish_date]
        final_time = params[:finish_time]
        final_string = final_date + " " + final_time +" "+ "-0430"
        final_datetime = DateTime.strptime(final_string, '%m/%d/%Y %H:%M:%S %P %:z')
        @promo.finish_date = final_datetime
        @promo.save
      end

      flash[:success] = "Promocion actualizada"
      redirect_to promotions_path
    else
      render 'edit'
    end
  end

#------------------------------------------------------------------

  def destroy
    @promo = Promotion.find(params[:id]).destroy
    if current_user.admin
      @promotions = Promotion.all.paginate(page: params[:page], per_page: 4)
    else
      @promotions = Promotion.where("store_id = ?", current_user.store).paginate(page: params[:page], per_page: 4)
    end
    flash[:success] = "Promocion borrada"

  end

  def filter
    @promotions = Promotion.where("lower(title) like (?)", "%" + params[:starts_with] + "%");
  end

#------------------------------------------------------------------

  private

  def promo_params
    params.require(:promotion).permit(:title, :rate, :price, :notification_body,
                                      :promo_price, :conditions, :image, :store_id,
                                      :init_date, :finish_date)
  end
#------------------------------------------------------------------


end

app/helpers/api/v1/promotions_helper.rb
module Api::V1::PromotionsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_promotion_content.html.erb
<% @promotions.each do |promo| %>
    <tr role="row" class="odd">

      <td><%=  promo.title %></td>
      <td><%= promo.price %></td>
      <td><%= promo.promo_price %></td>

      <% if promo.notification_body != nil %>
          <% if promo.notification_body != '' %>

              <td><h6><%= promo.count_notification %></h6></td>
              <td><%= link_to "Enviar notificacion", notifications_new_path(promo_id: promo.id), class: 'btn btn-info btn-sm btn-icon icon-left' %></td>
          <% else %>
              <td><h6>N/A</h6></td>
              <td>N/A</td>
          <% end %>

      <% else %>
          <td><h6>N/A</h6></td>
          <td>N/A</td>

      <% end %>




      <td>
        <% if can? :update, promo %>
            <%= link_to "Editar", edit_promotion_path(promo), class: "btn btn-secondary btn-sm btn-icon icon-left" %>
            <%= link_to "Eliminar", "/promotions/#{promo.id}", {data: {confirm: "Esta seguro que desea eliminar la promocion '#{promo.title}'?"}, :method => :delete, remote: true, class: "btn btn-danger btn-sm btn-icon icon-left"} %>
        <% end %>
      </td>
    </tr>
<% end %>

app/views/promotions/destroy.js.erb
$(".promo-index").html("<%= escape_javascript(render 'promotion_content') %>")

app/views/promotions/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default" style="width: 100%;">
      <div class="panel-heading">
        <h3 class="panel-title">Editar promocion</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@promo, html: {multipart: true}) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>

            <%= f.label :price %>
            <%= f.text_field :price, class: 'form-control' %>

            <%= f.label :promo_price, "Precio de promocion" %>
            <%= f.text_field :promo_price, class: 'form-control' %>

            <div class="form-group">
              <div class="col-md-6">
                <div class="col-md-12">
                  <div class="col-md-8">
                    <%= f.label :initial_date, 'Fecha de inicio', class: 'control-label' %>
                  </div>
                  <div class="col-md-4">

                    <%= f.label :initial_date, 'Hora', class: 'control-label' %>
                  </div>
                </div>
                <div class='date-and-time'>

                  <input class="form-control datepicker" type="text" name="initial_date" id="initial_date"
                         required="true">

                  <input type="text" class="form-control timepicker" name="initial_time"
                         required="true" data-template="dropdown"
                         data-show-seconds="true" value="<%= @promo.initial_date.strftime("%I:%M%p") %>" data-show-meridian="true"
                         data-minute-step="5" data-second-step="5">

                </div>
              </div>

              <div class="col-md-6">
                <div class="col-md-12">
                  <div class="col-md-8">
                    <%= f.label :finish_date, 'Fecha de fin', class: 'control-label' %>
                  </div>
                  <div class="col-md-4">

                    <%= f.label :finish_date, 'Hora', class: 'control-label' %>
                  </div>
                </div>
                <div class='date-and-time'>

                  <input class="form-control datepicker" type="text" name="finish_date" id="finish_date" required="true">

                  <input type="text" class="form-control timepicker" name="finish_time" required="true"
                         data-template="dropdown"
                         data-show-seconds="true" value="<%= @promo.finish_date.strftime("%I:%M%p") %>" data-show-meridian="true"
                         data-minute-step="5" data-second-step="5">

                </div>
              </div>
            </div>



            <%= f.label :conditions, "Condiciones" %>
            <%= f.text_field :conditions, class: 'form-control' %>
            <% if current_user.admin %>
                <div class="form-group">
                  <%= f.label :store, "Locales comerciales" %>
                  <%= f.collection_select(:store_id, Store.all, :id, :name, {}, {class: 'form-control'}) %>
                </div>
            <% end %>

            <div class="form-group">

              <div class="row">
                <label class="btn glyphicon glyphicon-camera"
                       data-toggle="tooltip" title="Añadir foto">
                  Imagen
                  <%= file_field_tag "image", accept: 'image/jpeg,image/gif,image/png',
                                     class: 'photo_upload', id: "img_file" %>
                  <%= content_tag(:div, tag(:img, {src: @promo.image.url, id: "img-preview",
                                                   height: "80", width: "150"}), id: "img-preview_div") %>
                </label>

              </div>

              <div class="row">
                <label id="clear-logo" class="btn glyphicon glyphicon-remove" onclick="remove_image('#img_file','#img-preview')"></label>
              </div>
            </div>
            <br>
            <br>

            <div class="col-md-3 col-md-offset-3">
              <%= link_to "Cancelar", :back, class: "btn btn-primary", style: 'width:100%;' %>

            </div>

            <div class="col-md-3 ">
              <%= f.submit "Guardar", class: "btn btn-primary", style: 'width:100%;' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript">
    $(document).ready(function () {

        $("#initial_date").datepicker('setDate', new Date(<%= @promo.initial_date.year %>,
                <%= @promo.initial_date.month   %> -1, <%= @promo.initial_date.day %>));
        $("#initial_date").datepicker('update');

        $("#finish_date").datepicker('setDate', new Date(<%= @promo.finish_date.year %>,
                <%= @promo.finish_date.month   %> -1, <%= @promo.finish_date.day %>));
        $("#finish_date").datepicker('update');



        var preview = $("#img-preview");

        $("#img_file").change(function (event) {
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function (e) {
                image_base64 = e.target.result;
                preview.attr("src", image_base64);
            };
            reader.readAsDataURL(file);
        });


    });
</script>

app/views/promotions/filter.js.erb
$(".promo-index").html("<%= escape_javascript(render 'promotion_content') %>")

app/views/promotions/index.html.erb
<% provide(:title, 'Promociones') %>
<h1> Promociones </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'nueva promocion', new_promotion_path, class: "btn btn-primary btn-sm btn-icon icon-left" %>
  </div>

  <% if current_user.admin %>

      <div class="row">

        <!--<div class="col-md-2" style="margin-right: -10%;">
          <label for="starts_with" class="control-label">Buscar</label>


        </div>-->


        <div class="col-md-4">
          <input id="starts_with" placeholder="Buscar promocion por titulo" name="starts_with" type="text" class="form-control"/>
        </div>
      </div>


  <% end %>

  <div class="panel-body">
    <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>

        <tr role="row">
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Titulo: actiamamvate to sort column ascending" style="width: 15%;">Titulo
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio: activate to sort column ascending" style="width: 10%;">Precio
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio promocional: activate to sort column ascending" style="width: 15%;">Precio
            promocional
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Numero: activate to sort column ascending">Numero
            de notificacion
          </th>

          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Notificacion: activate to sort column ascending">Notificacion
          </th>
          <th tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">Acciones</th>
        </tr>
        </thead>

        <tbody class="middle-align promo-index">


        <%= render 'promotion_content' %>


        </tbody>
      </table>

      <div class="row">

        <div class="col-md-4">
          <%= will_paginate %>
        </div>
        <div class="col-md-2">
          <br>
          <br>
          <% if will_paginate %>
              <%= select_tag :per_page,"<option>5</option><option>10</option><option>15</option><option>20</option><option>50</option>".html_safe, class: 'from-control' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $("#starts_with").keyup(function (event) {
        var search_field = $('#starts_with');


        var jsonPost = { starts_with: search_field.val().toLowerCase() }


        $.ajax({
            type: 'POST',
            url: '/promotions/filter',
            data: jsonPost,
            dataType: 'script'
        });


    });
    $('#per_page').change(function () {
        var select = $('#per_page');
        var jsonPost = { per_page: select.val() }


        $.ajax({
            type: 'GET',
            url: '/promotions/',
            data: jsonPost,
            dataType: 'script'
        });

    });

</script>

app/views/promotions/index.js.erb
$(".promo-index").html("<%= escape_javascript(render 'promotion_content') %>")

app/views/promotions/new.html.erb
<% provide(:title, 'Nueva promo') %>


<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default" style="width: 100%;">
      <div class="panel-heading">
        <h3 class="panel-title">Nueva promocion</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@promo, html: {multipart: true}) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <div class="form-group">

              <%= f.label :title, class: 'control-label' %>
              <%= f.text_field :title, class: 'form-control', :required => true %>
            </div>

            <div class="form-group">

              <%= f.label :price, class: 'control-label' %>
              <%= f.text_field :price, class: 'form-control' %>
            </div>

            <div class="form-group">

              <%= f.label :promo_price, "Precio de promocion", class: 'control-label' %>
              <%= f.text_field :promo_price, class: 'form-control' %>
            </div>

            <div class="form-group">
              <div class="col-md-6">
                <div class="col-md-12">
                  <div class="col-md-8">
                    <%= f.label :initial_date, 'Fecha de inicio', class: 'control-label' %>
                  </div>
                  <div class="col-md-4">

                    <%= f.label :initial_date, 'Hora', class: 'control-label' %>
                  </div>
                </div>
                <div class='date-and-time'>

                  <input class="form-control datepicker" type="text" name="initial_date" id="initial_date"
                         required="true">


                  <input type="text" class="form-control timepicker" name="initial_time"
                         required="true" data-template="dropdown"
                         data-show-seconds="true" data-default-time="11:25 AM" data-show-meridian="true"
                         data-minute-step="5" data-second-step="5">

                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-6">
                <div class="col-md-12">
                  <div class="col-md-8">
                    <%= f.label :finish_date, 'Fecha de fin', class: 'control-label' %>
                  </div>
                  <div class="col-md-4">

                    <%= f.label :finish_date, 'Hora', class: 'control-label' %>
                  </div>
                </div>
                <div class='date-and-time'>

                  <input class="form-control datepicker" type="text" name="finish_date" id="finish_date" required="true">


                  <input type="text" class="form-control timepicker" name="finish_time" required="true"
                         data-template="dropdown"
                         data-show-seconds="true" data-default-time="11:25 AM" data-show-meridian="true"
                         data-minute-step="5" data-second-step="5">

                </div>
              </div>
            </div>


            <div class="form-group">
              <%= f.label :conditions, "Condiciones", class: 'control-label' %>
              <%= f.text_field :conditions, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :notification_body, "Texto de notificacion", class: 'control-label' %>
              <%= f.text_field :notification_body, class: 'form-control' %>
            </div>



            <% if current_user.admin %>
                <div class="form-group">
                  <%= f.label :store, "Locales comerciales", class: 'control-label' %>
                  <%= f.collection_select(:store_id, Store.all, :id, :name, {}, {class: 'form-control', :required => true}) %>
                </div>

            <% end %>


            <div class="form-group">
              <div class="row">
                <label class="btn glyphicon glyphicon-camera"
                       data-toggle="tooltip" title="Añadir foto">
                  Imagen
                  <%= file_field_tag "image", accept: 'image/jpeg,image/gif,image/png',
                                     class: 'photo_upload', id: "img_file", :required => true %>
                  <%= content_tag(:div, tag(:img, {id: "img-preview",src: "#", height: "80", width: "150"}), id: "img-preview_div") %>

                </label>

              </div>


              <div class="row">
                <label id="clear-logo" class="btn glyphicon glyphicon-remove" onclick="remove_image('#img_file','#img-preview')"></label>
              </div>
              <%= label_tag(name = :campo_obligatorio, content_or_options = nil, options = {id: 'label_field', style: 'display: none; color: red;'}) %>
            </div>

            <br>
            <br>

            <%= f.submit "Guardar", id: 'submit_promo', class: "btn btn-primary", style: 'width:100%;' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>


    $('#submit_promo').click(function () {

        var file_field = $('#img_file');

        if (file_field.val().length == 0) {
            $('#label_field').css('display', 'block')
        }
    });


    $(document).ready(function () {

        var preview = $("#img-preview");

        $("#img_file").change(function (event) {
            var input = $(event.currentTarget);
            var file = input[0].files[0];
            var reader = new FileReader();
            reader.onload = function (e) {
                image_base64 = e.target.result;
                preview.attr("src", image_base64);
            };
            reader.readAsDataURL(file);
        });

    });


</script>

app/views/promotions/show.html.erb
<% provide(:title, 'Promocione') %>
<h1> Promocion </h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to 'nueva promocion', new_store_promotion_path(@promo.store), class:"btn btn-primary btn-sm btn-icon icon-left"  %>
  </div>
  <div class="panel-body">
    <div id="example-2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <table class="table table-bordered table-striped dataTable no-footer" id="example-2" role="grid" aria-describedby="example-2_info">
        <thead>
        <tr role="row">
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Titulo: activate to sort column ascending" style="width: 176px;">Titulo
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio: activate to sort column ascending" style="width: 116px;">Precio
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Precio promocional: activate to sort column ascending" style="width: 236px;">Precio
            promocional
          </th>
          <th  tabindex="0" aria-controls="example-2" rowspan="1" colspan="1" aria-label="Acciones: activate to sort column ascending">Acciones</th>
        </tr>
        </thead>

        <tbody class="middle-align">

            <%= render @promo %>

        </tbody>
      </table>

    </div>
  </div>
</div>