config/routes.rb
Rails.application.routes.draw do

  get 'notifications/new'

  post 'notifications/create' => 'notifications#create'

  get 'reports/show'

  get 'reports/export_to_excel_users'

  post 'reports/filter' => 'reports#filter'

  root 'static_pages#home'
  get 'successfull_password_changed', to: 'static_pages#password_changed'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'api/v1/users/create' => 'api/v1/users#create', :defaults => {:format => 'json'}

  post '/api/v1/sessions/create_fb' => 'api/v1/sessions#create_fb', :defaults => {:format => 'json'}

  match '*any' => 'api/api#options', :via => [:options]
  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/orders/subregion_options' => 'notifications#subregion_options'

  get '/cantons/subregion_options' => 'notifications#subsubregion_options'

  post "/promotions/filter" => 'promotions#filter'

  post "/events/filter" => 'events#filter'

  post "/stores/filter" => 'stores#filter'

  post "/place_of_interests/filter" => 'place_of_interests#filter'

  resources :promotions

  resources :users

  get 'admin_promotions' => 'promotions#admin_index'

  resources :events

  resources :stores

  resources :place_of_interests

  resources :password_resets, only: [:edit, :update]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sessions
      resources :users
      resources :promotions
      resources :events
      resources :stores
      resources :place_of_interests
      post 'reset_password', to: 'passwords#create'
      post 'update_token_device', to: 'users#update_user_device'

    end
  end

  post '/api/v1/comments/:event_id/:body' => 'api/v1/comments#create'
  post '/api/v1/reviews/:promo_id/rate/:rate' => 'api/v1/reviews#vote'

  get '/api/v1/reviews/:promo_id' => 'api/v1/reviews#show_user_vote'

  get '/api/v1/get_events' => 'api/v1/events#last'

  get '/api/v1/get_last_events' => 'api/v1/events#last'

  get '/api/v1/get_last_projections' => 'api/v1/events#last_projections'

  get '/api/v1/get_last_promotions' => 'api/v1/promotions#last'

  get '/api/v1/get_countries' => 'api/v1/country#index'

  get '/api/v1/comments/:event_id/:index' => 'api/v1/comments#index_for_event'

  get '/api/v1/get_restaurants' => 'api/v1/stores#index_rest'

  get '/api/v1/get_kioscos' => 'api/v1/stores#index_kiosco'

  get '/api/v1/get_enter' => 'api/v1/place_of_interests#index_enter'
  get '/api/v1/get_cult' => 'api/v1/place_of_interests#index_cult'
  get '/api/v1/get_depor' => 'api/v1/place_of_interests#index_depor'
  get '/api/v1/get_adic' => 'api/v1/place_of_interests#index_adic'

  get '/api/v1/restaurant/:pag' => 'api/v1/stores#paginate_rest'

  get '/api/v1/kiosco/:pag' => 'api/v1/stores#paginate_kiosco'

  get '/api/v1/paginate_event/:pag' => 'api/v1/events#paginate_event'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="left" >
    <ul>
      <li><%= link_to "Inversor 1",   about_path %></li>
      <li><%= link_to "Inversor 2", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <nav class="navbar navbar-inverse">
    <div class="sidebar-menu-inner ps-container ps-active-y">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <% if logged_in? %>

            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Home', root_path, class: 'navbar-brand' %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <% if current_user.admin %>
                    <li><%= link_to 'Locales comerciales', stores_path %></li>
                <% end %>

                <% if current_user.admin %>
                    <li><%= link_to 'Sitios de interes', place_of_interests_path %></li>
                <% end %>

                <li><%= link_to 'Promociones', promotions_path %></li>









                <% if current_user.admin %>
                    <li><a href="/events">Eventos</a></li>
                    <li><%= link_to "Notificaciones", notifications_new_path %></li>
                <% end %>


              </ul>

              <nav>
                <ul class="nav navbar-nav navbar-right">
                  <% if current_user.admin %>

                      <li><%= link_to "Usuarios", users_path %></li>

                      <li><%= link_to "Reportes", reports_show_path %></li>


                  <% end %>

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                </ul>
              </nav>


        <% end %>

        </div>
      </div>
    </div>
  </nav>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_slide_bar_menu.html.erb
<% if logged_in? %>
    <div class="sidebar-menu toggle-others fixed">
      <div class="sidebar-menu-inner ps-container ps-active-y">
        <header class="logo-env"> <!-- logo -->
          <div class="logo">

            <a href="<%= root_path %>">

              <%= image_tag 'logo.png', width: '80' %>
            </a>


          </div>
          <div class="mobile-menu-toggle visible-xs">
            <a href="#" data-toggle="user-info-menu"> <i class="fa-bell-o"></i>
              <span class="badge badge-success">7</span>
            </a> <a href="#" data-toggle="mobile-menu"> <i class="fa-bars"></i> </a></div>

        </header>


        <ul id="main-menu" class="main-menu">
          <li>
            <a href="<%= root_path %>">
              <i class="linecons-cog"></i>
              <span class="title">Dashboard</span>
            </a>
          </li>

          <li class="has-sub">
            <% if current_user.admin %>
                <a href="<%= stores_path %>">
                  <i class="fa-cutlery"></i>
                  <span>Gastronomia</span>
                </a>
                <ul>
                  <li>
                    <a href="/stores/?kind=<%= RESTAURANT %>">
                      <span class="title">Restaurantes</span>
                    </a>
                  </li>
                  <li>
                    <a href="/stores/?kind=<%= KIOSCO %>">
                      <span class="title">Kioscos</span>
                    </a>
                  </li>
                </ul>
            <% end %>
          </li>

          <li class="has-sub">

            <% if current_user.admin %>
                <a href="<%= place_of_interests_path %>">
                  <i class="fa-cube"></i>
                  <span>Sitios de interes</span>
                </a>
                <ul>
                  <li>
                    <a href="/place_of_interests/?kind=<%= DEPORTIVO %>">
                      <span class="title">Espacios Deportivos</span>
                    </a>
                  </li>
                  <li>
                    <a href="/place_of_interests/?kind=<%= CULTURAL %>">
                      <span class="title">Espacios Culturales</span>
                    </a>
                  </li>
                  <li>
                    <a href="/place_of_interests/?kind=<%= ENTRETENIMIENTO %>">
                      <span class="title">Entretenimiento</span>
                    </a>
                  </li>

                  <li>
                    <a href="/place_of_interests/?kind=<%= ADICIONALES %>">
                      <span class="title">Adicionales</span>
                    </a>
                  </li>
                </ul>

            <% end %>

          </li>


          <li>

            <a href="<%= promotions_path %>">
              <i class="fa-gift"></i>
              <span>Promociones</span>
            </a>


          </li>

          <li>
            <% if current_user.admin %>
                <a href="<%= events_path %>">
                  <i class="fa-calendar-o"></i>
                  <span>Eventos</span>
                </a>


            <% end %>


          </li>


          <li>


            <a href="<%= notifications_new_path %>">
              <i class="fa-comments"></i>
              <span>Notificaciones</span>
            </a>

          </li>

          <li>
            <% if current_user.admin %>
                <a href="<%= users_path %>">
                  <i class="fa-users"></i>
                  <span>Usuarios</span>
                </a>

            <% end %>
          </li>

          <li>
            <% if current_user.admin %>
                <a href="<%= reports_show_path %>">
                  <i class="fa fa-bar-chart"></i>
                  <span>Reportes</span>
                </a>


            <% end %>
          </li>

          <li>
            <a href="<%= logout_path %>" data-method="delete">
              <i class="fa-sign-out"></i>
              <span>Logout</span>
            </a>


          </li>

        </ul>


      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://connect.facebook.net/en_US/all.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9AgsmuFD2CaWOMUbfsv6jUxcJRAuGfdc&signed_in=true&libraries=places"
          type="text/javascript"></script>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="page-body">
<div class="page-container ">
<%= render 'layouts/slide_bar_menu'  %>


  <div class="main-content">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

  </div>


</div>



</body>
</html>

app/views/layouts/login.html.erb
<% provide(:title, "Log in") %>
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Arimo:400,700,400italic" id="style-resource-1">
  <script src="https://connect.facebook.net/en_US/all.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9AgsmuFD2CaWOMUbfsv6jUxcJRAuGfdc&signed_in=true&libraries=places"
          type="text/javascript"></script>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="page-body login-page">




  <%= yield %>

</div>
</body>
</html>